/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
    kotlin("jvm") version "2.1.10"
}

subprojects {
    apply(plugin = "kotlin")
    dependencies {
        api(rootProject)
        api(kotlin("script-runtime"))
        kotlinScriptDef(rootProject)
    }
}

allprojects {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
        maven("https://hub.spigotmc.org/nexus/content/repositories/public")
        maven("https://papermc.io/repo/repository/maven-public/")
        maven("https://maven.enginehub.org/repo/")
        maven("https://oss.sonatype.org/content/repositories/snapshots/")
        maven("https://repo.codemc.org/repository/maven-public")
        maven("https://repo.mvdw-software.com/content/groups/public/")
        maven("https://www.uskyblock.ovh/maven/dependencies/")
        maven("https://www.uskyblock.ovh/maven/uskyblock/")
        maven("https://repo.maven.apache.org/maven2/")
        maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")

        maven("https://repo.onarandombox.com/content/groups/public")
        maven("https://hub.spigotmc.org/nexus/content/groups/public/")
        maven("https://jitpack.io")
        maven("https://repo.minebench.de/")
        maven("https://repo.maven.apache.org/maven2/")
    }
}

group = "ovh.uskyblock"
version = "3.2.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
