commit_message: "[ci skip]"
files:
  - source: /uSkyBlock-Core/src/main/po/keys.pot
    translation: /uSkyBlock-Core/src/main/po/%locale_with_underscore%.po
    languages_mapping:
      locale_with_underscore:
        ar: ar
        cs: cs
        da: da
        de: de
        en-GB: en_GB
        es-ES: es
        fr: fr
        hu: hu
        id: id
        it: it
        ja: ja
        ko: ko
        nl: nl
        pl: pl
        pt-BR: pt_BR
        pt-PT: pt_PT
        ru: ru
        sv-SE: sv
        th: th
        tr: tr
        uk: uk
        vi: vi_VN
        zh-CN: zh_CN
        zh-TW: zh_TW
