commit_message: "[ci skip]"
files:
  - source: /uSkyBlock-Core/src/main/po/keys.pot
    translation: /uSkyBlock-Core/src/main/po/%locale_with_underscore%.po
    languages_mapping:
      locale_with_underscore:
        ar: ar
        be: be
        bg: bg
        bn: bn
        bs: bs
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        en-GB: en_GB
        et: et
        es-ES: es
        eu: eu
        fa: fa
        fi: fi
        fil: fil
        fr: fr
        ga: ga
        gl: gl
        he: he
        hi: hi
        hr: hr
        hu: hu
        id: id
        is: is
        it: it
        ja: ja
        ko: ko
        lb: lb
        lt: lt
        lv: lv
        mk: mk
        ms: ms
        mt: mt
        nb: nb
        nl: nl
        pl: pl
        pt-BR: pt_BR
        pt-PT: pt_PT
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sq: sq
        sr: sr
        sv-SE: sv
        th: th
        tr: tr
        uk: uk
        ur: ur
        vi: vi_VN
        zh-CN: zh_CN
        zh-TW: zh_TW
