/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "uSkyBlock"
include(":uSkyBlock-FAWE")
include(":bukkit-utils")
include(":uSkyBlock-Core")
include(":uSkyBlock-API")
include(":uSkyBlock-Plugin")
include(":po-utils")
include(":uSkyBlock-APIv2")
