/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":bukkit-utils"))
    api(project(":po-utils"))
    api(project(":uSkyBlock-API"))
    api(project(":uSkyBlock-APIv2"))
    api(libs.io.papermc.paperlib)
    api(libs.org.bstats.bstats.bukkit)
    api(libs.com.google.inject.guice)
    api(libs.org.jetbrains.annotations)
    testImplementation(testFixtures(project(":bukkit-utils")))
    testImplementation(libs.org.hamcrest.hamcrest)
    testImplementation(libs.org.hamcrest.hamcrest.library.x1)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.mockito.mockito.core)
    compileOnly(libs.net.milkbowl.vault.vaultapi)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.org.mvplugins.multiverse.core.multiverse.core)
    compileOnly(libs.org.mvplugins.multiverse.inventories.multiverse.inventories)
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
    testImplementation(libs.com.sk89q.worldedit.worldedit.bukkit)
    compileOnly(libs.com.sk89q.worldguard.worldguard.bukkit)
    compileOnly(libs.com.google.guava.guava)
    compileOnly(libs.com.google.code.gson.gson.x1)
    compileOnly(libs.be.maximvdw.mvdwplaceholderapi) {
        exclude(group = "*", module = "*")
    }
    compileOnly(libs.net.kyori.adventure.api)
    compileOnly(libs.net.kyori.adventure.platform.bukkit)
    compileOnly(libs.org.apache.commons.commons.lang3)
    compileOnly(libs.org.apache.httpcomponents.httpclient)
    compileOnly(libs.org.apache.maven.maven.artifact)
}

description = "uSkyBlock-Core"

java {
    withJavadocJar()
}
