import buildlogic.i18n.Dialect
import buildlogic.i18n.ExtractTranslationTask
import buildlogic.i18n.GenerateExtraTranslationsTask
import buildlogic.i18n.GenerateSupportedLocalesTask
import buildlogic.i18n.MergeDomainTranslationsTask
import buildlogic.i18n.TranslationDomain

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(projects.bukkitUtils)
    api(projects.poUtils)
    api(projects.uSkyBlockAPI)
    api(projects.uSkyBlockAPIv2)
    api(libs.io.papermc.paperlib)
    api(libs.org.bstats.bstats.bukkit)
    api(libs.com.google.inject.guice)
    api(libs.org.jetbrains.annotations)
    testImplementation(testFixtures(projects.bukkitUtils))
    testImplementation(libs.org.hamcrest.hamcrest)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.net.kyori.adventure.api)
    testImplementation(libs.net.kyori.adventure.text.minimessage)
    testImplementation(libs.net.kyori.adventure.text.serializer.legacy)
    testImplementation(libs.org.apache.commons.commons.lang3)
    implementation(libs.org.xerial.sqlite.jdbc)
    implementation(libs.net.kyori.adventure.text.serializer.plain)
    compileOnly(libs.net.milkbowl.vault.vaultapi)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.org.mvplugins.multiverse.core.multiverse.core)
    testImplementation(libs.org.mvplugins.multiverse.core.multiverse.core) {
        // Tests only need Multiverse's own (self-contained) classes; its transitive
        // dependencies include JitPack-only artifacts unavailable from our repositories.
        isTransitive = false
    }
    compileOnly(libs.org.mvplugins.multiverse.inventories.multiverse.inventories)
    // WorldEdit/WorldGuard are provided by the server at runtime; we only compile against their API.
    // Their published metadata strict-pins bundled libraries the server already ships (guava, gson),
    // and WorldGuard drags in its own older WorldEdit lineage. Exclude both so a single WorldEdit
    // (our version) and the catalog's guava/gson win the compile classpath instead of conflicting.
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit) {
        exclude(group = "com.google.guava")
        exclude(group = "com.google.code.gson")
    }
    testImplementation(libs.com.sk89q.worldedit.worldedit.bukkit)
    compileOnly(libs.com.sk89q.worldguard.worldguard.bukkit) {
        exclude(group = "com.sk89q.worldedit")
        exclude(group = "com.google.guava")
        exclude(group = "com.google.code.gson")
    }
    compileOnly(libs.com.google.guava.guava)
    compileOnly(libs.com.google.code.gson.gson)
    compileOnly(libs.net.kyori.adventure.api)
    compileOnly(libs.net.kyori.adventure.platform.bukkit)
    compileOnly(libs.net.kyori.adventure.text.minimessage)
    compileOnly(libs.net.kyori.adventure.text.serializer.legacy)
    compileOnly(libs.org.apache.commons.commons.lang3)
    compileOnly(libs.org.apache.httpcomponents.client5.httpclient5)
    compileOnly(libs.org.apache.maven.maven.artifact)
}

description = "uSkyBlock-Core"

// ---------------------------------------------------------------------------
// i18n message-catalog build.
//
// The runtime bundle (i18n.zip) is assembled with NO external tools: the domain
// catalogs are merged and the Pirate/Kitteh joke locales generated by the tested
// Kotlin in buildSrc (buildlogic.i18n). Only `extractTranslation` still needs the
// gettext toolchain (xgettext); it is not on the default build path — it runs from
// the `translation`/`updateTranslation` tasks and the CI drift check.
// ---------------------------------------------------------------------------

val i18nSourceDir = layout.projectDirectory.dir("src/main/i18n")
val generatedI18nDir = layout.buildDirectory.dir("generated/i18n")
val domainTemplateFiles = TranslationDomain.entries.map { i18nSourceDir.file("keys.${it.id}.pot") }
val supportedLocalesFile = generatedI18nDir.map { it.file("supported-locales.txt") }
val jokeLocaleKeys = listOf(Dialect.PIRATE.localeKey, Dialect.KITTEH.localeKey)

val extractTranslation = tasks.register<ExtractTranslationTask>("extractTranslation") {
    group = "translation"
    description = "Extracts translatable strings into domain-specific .pot files (needs xgettext)"
    javaSources.from(
        fileTree(project(":bukkit-utils").projectDir.resolve("src/main/java")) { include("**/*.java") },
        fileTree(projectDir.resolve("src/main/java")) { include("**/*.java") },
    )
    projectRootDir.set(rootProject.layout.projectDirectory)
    combinedPotFile.set(generatedI18nDir.map { it.file("keys.all.pot") })
    mergedPotFile.set(generatedI18nDir.map { it.file("keys.pot") })
    playerFacingPotFile.set(i18nSourceDir.file("keys.player_facing.pot"))
    adminOpsPotFile.set(i18nSourceDir.file("keys.admin_ops.pot"))
    systemDebugPotFile.set(i18nSourceDir.file("keys.system_debug.pot"))
}

// These two consume the committed .pot templates, which `extractTranslation` also writes. A plain
// `build` never runs `extractTranslation` (it stays off the default, tool-free path), so there is no
// dependency between them. But when both are requested together — e.g. the `translation` aggregator,
// or CI's `./gradlew build translation` — the templates must be regenerated before they are consumed.
// `mustRunAfter` orders that case without forcing `extractTranslation` to run for a plain `build`.
val mergeDomainTranslations = tasks.register<MergeDomainTranslationsTask>("mergeDomainTranslations") {
    group = "translation"
    description = "Merges domain-specific .po files into per-locale .po files (tool-free)"
    mustRunAfter(extractTranslation)
    i18nDir.set(i18nSourceDir)
    outputDir.set(generatedI18nDir.map { it.dir("locales") })
}

val generateExtraTranslations = tasks.register<GenerateExtraTranslationsTask>("generateExtraTranslations") {
    group = "translation"
    description = "Generates the Pirate and Kitteh joke locales (tool-free)"
    mustRunAfter(extractTranslation)
    domainTemplates.from(domainTemplateFiles)
    outputDir.set(generatedI18nDir.map { it.dir("extra") })
}

val generateSupportedLocales = tasks.register<GenerateSupportedLocalesTask>("generateSupportedLocales") {
    group = "translation"
    description = "Generates a stable list of supported locale keys from .po files"
    mergedLocalesDir.set(mergeDomainTranslations.flatMap { it.outputDir })
    extraLocaleKeys.set(jokeLocaleKeys)
    outputFile.set(supportedLocalesFile)
}

val i18nZip = tasks.register<Zip>("i18nZip") {
    group = "build"
    description = "Zips the .po files into i18n.zip"
    from(mergeDomainTranslations.flatMap { it.outputDir }) { include("*.po") }
    from(generateExtraTranslations.flatMap { it.outputDir }) { include("*.po") }
    from(generateSupportedLocales.flatMap { it.outputFile })
    archiveFileName.set("i18n.zip")
    // Keep archive output outside processResources destination to avoid self-copy truncation.
    destinationDirectory.set(generatedI18nDir)
}

val i18nZipFile = i18nZip.flatMap { it.archiveFile }

tasks.processResources {
    from(i18nZipFile)
    inputs.file(i18nZipFile)

    val props = mapOf(
        "projectVersion" to project.version,
        "buildNumber" to (System.getenv("GITHUB_RUN_NUMBER") ?: "DEV"),
        "gsonVersion" to libs.versions.com.google.code.gson.gson.get(),
        "guiceVersion" to libs.versions.com.google.inject.guice.get(),
        "guavaVersion" to libs.versions.com.google.guava.guava.get(),
        "adventureApiVersion" to libs.versions.net.kyori.adventure.api.get(),
        "adventureBukkitVersion" to libs.versions.net.kyori.adventure.platform.bukkit.get(),
        "apacheCommonsVersion" to libs.versions.org.apache.commons.commons.lang3.get(),
        "apacheHttpVersion" to libs.versions.org.apache.httpcomponents.client5.httpclient5.get(),
        "mavenArtifactVersion" to libs.versions.org.apache.maven.maven.artifact.get(),
        "sqliteVersion" to libs.versions.org.xerial.sqlite.jdbc.get()
    )
    inputs.properties(props)
    filesMatching("plugin.yml") {
        expand(props)
    }
}

tasks.register("updateTranslation") {
    group = "translation"
    description = "Updates translation sources for Crowdin"
    dependsOn(extractTranslation, mergeDomainTranslations, generateExtraTranslations)
}
