/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":bukkit-utils"))
    implementation(project(":po-utils"))
    implementation(project(":uSkyBlock-API"))
    implementation(project(":uSkyBlock-APIv2"))
    testImplementation(project(":bukkit-utils", "testsJar"))
}

description = "uSkyBlock-Core"
