import java.time.LocalDate
import java.time.format.DateTimeFormatter

/*
 * This file was generated by the Gradle 'init' task.
 */


plugins {
    java
    `maven-publish`
    id("com.gradleup.shadow") version "8.3.6"
}

val version = "cong-" + LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")) // 替换为实际版本号


tasks {
    register<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("buildPlugin") {
        group = "plugin"
        from(sourceSets.main.map { it.output })
        archiveClassifier.set("")
        configurations = listOf(project.configurations.runtimeClasspath.get())
        doLast {
            println(archiveFile.get())
        }
    }
}

dependencies {
    implementation(project(":uSkyBlock-API"))
    implementation(project(":uSkyBlock-Core"))
    implementation(project(":uSkyBlock-FAWE"))
}

description = "uSkyBlock-Plugin"
