/*
 * This file was generated by the Gradle 'init' task.
 */


dependencies {
    implementation(project(":uSkyBlock-API"))
    implementation(project(":uSkyBlock-Core"))
    implementation(project(":uSkyBlock-FAWE"))
}

description = "uSkyBlock-Plugin"
