/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":uSkyBlock-API"))
    api(project(":uSkyBlock-Core"))
    api(project(":uSkyBlock-FAWE"))
}

description = "uSkyBlock-Plugin"
