/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(projects.uSkyBlockCore)
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.core) {
        exclude(group = "*")
    }
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.bukkit) {
        exclude(group = "*")
    }
    compileOnly(libs.org.spigotmc.spigot.api)
    // See uSkyBlock-Core: WorldEdit's metadata strict-pins the guava/gson the server ships; drop them
    // so the catalog's versions (required by spigot-api 26.3) win the compile classpath.
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit) {
        exclude(group = "com.google.guava")
        exclude(group = "com.google.code.gson")
    }
}

description = "uSkyBlock-FAWE"
