/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":uSkyBlock-Core"))
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.core)
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.bukkit)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
}

description = "uSkyBlock-FAWE"
