/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":uSkyBlock-Core"))
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.core) {
        exclude(group = "*")
    }
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.bukkit) {
        exclude(group = "*")
    }
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
}

description = "uSkyBlock-FAWE"

java {
    withJavadocJar()
}
