/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.annotations)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.hamcrest.hamcrest)
    testImplementation(libs.org.hamcrest.hamcrest.library.x1)
}

description = "po-utils"

java {
    withJavadocJar()
}
