/*
 * This file was generated by the Gradle 'init' task.
 */


dependencies {
    implementation("org.jetbrains:annotations:23.0.0")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.9.0")
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("org.hamcrest:hamcrest-library:2.2")
}

description = "po-utils"

java {
    withJavadocJar()
}
