/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/public")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public")
    }

    maven {
        url = uri("https://repo.mvdw-software.com/content/groups/public/")
    }

    maven {
        url = uri("https://www.uskyblock.ovh/maven/dependencies/")
    }

    maven {
        url = uri("https://www.uskyblock.ovh/maven/uskyblock/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.onarandombox.com/content/groups/public/")
    }
}

group = "ovh.uskyblock"
version = "3.2.0-SNAPSHOT"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
    val standardOptions = options as StandardJavadocDocletOptions
    // Define @implNote so the Javadoc tool recognizes it
    standardOptions.tags("implNote:a:Implementation Note:")
    // 2. Suppress the "missing" check in doclint
    // "all,-missing" means: check everything EXCEPT missing comments
    standardOptions.addStringOption("Xdoclint:all,-missing", "-quiet")
}
