/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("java-test-fixtures")
}

dependencies {
    api(project(":po-utils"))
    api(libs.org.spigotmc.spigot.api)
    api(libs.net.milkbowl.vault.vaultapi)
    testImplementation(libs.org.hamcrest.hamcrest.core)
    testImplementation(libs.org.hamcrest.hamcrest.library)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.com.google.code.gson.gson)

    testFixturesApi(libs.org.spigotmc.spigot.api)
    testFixturesApi(libs.org.mockito.mockito.core)
    testFixturesApi(libs.org.hamcrest.hamcrest.library)
}

description = "bukkit-utils"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
