/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":po-utils"))
}

description = "bukkit-utils"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

configurations {
    create("testsJar") {
        isCanBeConsumed = true
        isCanBeResolved = false
        outgoing.artifact(testsJar)
    }
}
