/*
 * This file was generated by the Gradle 'init' task.
 */


dependencies {
    implementation("org.jetbrains:annotations:23.0.0")
    compileOnly("org.spigotmc:spigot-api:1.20.6-R0.1-SNAPSHOT")
}

description = "uSkyBlock-APIv2"

java {
    withJavadocJar()
}
