/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.annotations)
    compileOnly(libs.org.spigotmc.spigot.api)
}

description = "uSkyBlock-APIv2"

java {
    withJavadocJar()
}
